name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubunru-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependenies
      run: |
        pip install -r requirements.txt
        pip install pytest streamlit
    - name: Run tests
      run: |
        pytest _test.py