name: Tesing Secret Variables

on:
  workflow_dispatch

env: 
  ACTIONS_SETUP_DEBUG: true 
jobs:
  text_context_varibales:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking the secret variables"
        run: |
          echo "Secret value ${{secrets.HF_TOKEN}}"

