name: Testing Workflow variable

on:
  workflow_dispatch

env:
  cloud: google-cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: hello
    steps:
      - name: "say hello Ashu it monday "
        run: echo " $Greeting $First_Name is using $cloud"
        env:
          First_Name: Ashu
    
